//! # Module-LWE Encryption with Homomorphic Addition
//!
//! Implements encryption and the additively homomorphic operation that enables
//! private vote tallying.
//!
//! ## Encryption
//!
//! Given a message bit m ∈ {0, 1} and public key (A, b):
//!
//! 1. Sample randomness vector r from CBD(eta)
//! 2. Sample noise vectors e₁ from CBD(eta), e₂ from CBD(eta) (single polynomial)
//! 3. Compute u = Aᵀ·r + e₁  (ciphertext component 1)
//! 4. Compute v = bᵀ·r + e₂ + ⌊q/2⌋·m  (ciphertext component 2)
//! 5. Return (u, v)
//!
//! ## Homomorphic Addition
//!
//! Given Enc(m₁) = (u₁, v₁) and Enc(m₂) = (u₂, v₂):
//!
//! (u₁ + u₂, v₁ + v₂) = Enc(m₁ + m₂)
//!
//! This works because encryption is linear in the message. The noise from both
//! ciphertexts accumulates additively, limiting the number of additions before
//! decryption failure.

use crate::keygen::PublicKey;
use crate::matrix::PolyVec;
use crate::params::PqhvParams;
use crate::poly::Poly;
use rand::RngCore;
use serde::{Deserialize, Serialize};

/// A ciphertext encrypting a single message bit (or a sum of bits after
/// homomorphic additions).
///
/// Consists of two components:
/// - `u`: A vector of k polynomials (k = module rank)
/// - `v`: A single polynomial containing the encrypted message
///
/// The ciphertext size is (k+1) polynomials, each with n coefficients mod q.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ciphertext {
    /// First ciphertext component: u = Aᵀ·r + e₁.
    /// This is a vector of k polynomials.
    pub u: PolyVec,

    /// Second ciphertext component: v = bᵀ·r + e₂ + ⌊q/2⌋·m.
    /// This is a single polynomial containing the encoded message plus noise.
    pub v: Poly,
}

/// Encrypt a single message bit using the public key.
///
/// # Arguments
///
/// * `pk` — The public key (A, b) generated by `keygen`.
/// * `message` — The message bit (0 or 1). Values > 1 are reduced mod 2.
/// * `params` — The parameter set.
/// * `rng` — A cryptographically secure random number generator.
///
/// # Returns
///
/// A `Ciphertext` encrypting the message bit.
///
/// # Security Properties
///
/// - The ciphertext is semantically secure under the Module-LWE assumption:
///   an adversary cannot distinguish Enc(0) from Enc(1) without the secret key.
/// - Each encryption uses fresh randomness (r, e₁, e₂), so encrypting the same
///   message twice produces different ciphertexts.
pub fn encrypt(
    pk: &PublicKey,
    message: u8,
    params: &PqhvParams,
    rng: &mut impl RngCore,
) -> Ciphertext {
    // Sample fresh randomness and noise
    let r = PolyVec::sample_cbd(params, params.eta, rng);
    let e1 = PolyVec::sample_cbd(params, params.eta, rng);
    let e2 = Poly::sample_cbd(params, params.eta, rng);

    // u = Aᵀ·r + e₁
    let u = pk.a.transpose().mul_vec(&r).add(&e1);

    // v = bᵀ·r + e₂ + ⌊q/2⌋·m
    let msg_poly = Poly::from_message(message, params);
    let v = pk.b.inner_product(&r).add(&e2).add(&msg_poly);

    Ciphertext { u, v }
}

/// Homomorphic addition of two ciphertexts.
///
/// If `ct1 = Enc(m₁)` and `ct2 = Enc(m₂)`, then the result encrypts `m₁ + m₂`.
///
/// # Noise Accumulation
///
/// The noise in the result is the sum of the noise in both inputs. After many
/// additions, the accumulated noise may exceed the decryption threshold (q/4),
/// causing decryption failure. Use `NoiseTracker` to monitor the noise budget.
///
/// # Arguments
///
/// * `ct1` — First ciphertext.
/// * `ct2` — Second ciphertext.
///
/// # Returns
///
/// A new ciphertext encrypting the sum of the two plaintext messages.
///
/// # Panics
///
/// Panics if the ciphertexts have incompatible dimensions.
pub fn add_ciphertexts(ct1: &Ciphertext, ct2: &Ciphertext) -> Ciphertext {
    Ciphertext {
        u: ct1.u.add(&ct2.u),
        v: ct1.v.add(&ct2.v),
    }
}

/// Homomorphic summation of multiple ciphertexts.
///
/// Convenience function that sums a slice of ciphertexts. Equivalent to
/// folding `add_ciphertexts` over the slice.
///
/// # Arguments
///
/// * `ciphertexts` — A non-empty slice of ciphertexts to sum.
///
/// # Returns
///
/// A single ciphertext encrypting the sum of all plaintext messages.
///
/// # Panics
///
/// Panics if the slice is empty.
pub fn sum_ciphertexts(ciphertexts: &[Ciphertext]) -> Ciphertext {
    assert!(!ciphertexts.is_empty(), "Cannot sum empty ciphertext list");
    let mut result = ciphertexts[0].clone();
    for ct in &ciphertexts[1..] {
        result = add_ciphertexts(&result, ct);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::keygen::keygen;
    use crate::params::PQHV_TEST;
    use rand::SeedableRng;
    use rand_chacha::ChaCha20Rng;

    fn test_rng() -> ChaCha20Rng {
        ChaCha20Rng::seed_from_u64(42)
    }

    #[test]
    fn test_encrypt_dimensions() {
        let mut rng = test_rng();
        let (pk, _) = keygen(&PQHV_TEST, &mut rng);
        let ct = encrypt(&pk, 1, &PQHV_TEST, &mut rng);

        assert_eq!(ct.u.k, PQHV_TEST.k);
        assert_eq!(ct.u.polys.len(), PQHV_TEST.k);
        assert_eq!(ct.v.coeffs.len(), PQHV_TEST.n);
    }

    #[test]
    fn test_encrypt_different_randomness() {
        let mut rng = test_rng();
        let (pk, _) = keygen(&PQHV_TEST, &mut rng);

        // Same message, different randomness → different ciphertexts
        let ct1 = encrypt(&pk, 1, &PQHV_TEST, &mut rng);
        let ct2 = encrypt(&pk, 1, &PQHV_TEST, &mut rng);
        assert_ne!(ct1, ct2);
    }

    #[test]
    fn test_add_ciphertexts_dimensions() {
        let mut rng = test_rng();
        let (pk, _) = keygen(&PQHV_TEST, &mut rng);
        let ct1 = encrypt(&pk, 0, &PQHV_TEST, &mut rng);
        let ct2 = encrypt(&pk, 1, &PQHV_TEST, &mut rng);
        let sum = add_ciphertexts(&ct1, &ct2);

        assert_eq!(sum.u.k, PQHV_TEST.k);
        assert_eq!(sum.v.coeffs.len(), PQHV_TEST.n);
    }

    #[test]
    fn test_sum_ciphertexts_single() {
        let mut rng = test_rng();
        let (pk, _) = keygen(&PQHV_TEST, &mut rng);
        let ct = encrypt(&pk, 1, &PQHV_TEST, &mut rng);
        let sum = sum_ciphertexts(&[ct.clone()]);
        assert_eq!(sum, ct);
    }

    #[test]
    #[should_panic(expected = "Cannot sum empty")]
    fn test_sum_ciphertexts_empty_panics() {
        let empty: Vec<Ciphertext> = vec![];
        sum_ciphertexts(&empty);
    }
}
